name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.8.0
      uses: actions/setup-node@v2
      with:
        node-version: "16.8.0"
        cache: "npm"
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: mkdir dist
    - run: node build.js
